language: rust

notifications:
  irc: "chat.freenode.net#Heather"
  email: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

script:
  - cd rs && cargo build
