language: c

notifications:
  irc: "chat.freenode.net#Heather"
  email: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
  - sudo apt-get update # Is this actually needed??

script:
 - raco exe -v rkt/tight.rkt

after_script:
 - ./tight --help
 - ./tight --init
 - ./tight
